#!/bin/sh
rm -f fort.*
cp nbody.v443 fort.90
cp ttr.sbody fort.91
../pep/pep <ttr.inp >ttr.out
../peputil/abcps >ttr.abc <<'End of input'
 &INPUT NAMES=T, LOOK=4, NSERIE=999, NOPRNT=1,
  OBSLIB=31,
 &END
End of input
