#!/bin/sh
rm -f fort.*
cp nbody.v452 fort.10
cp tv1.vko fort.64
../pep/pep <tv2.inp >tv2.out
../peputil/abcps >tv2.abc <<'End of input'
 &INPUT NAMES=T, LOOK=4, NSERIE=999, NOPRNT=1,
  OBSLIB=31,
 &END
End of input
