#!/bin/sh
if [ $# != 3 ]
then
	echo 'Error in syntax'
	exit
fi

# Initial cleanup
rm -f fort.*

# Do appropriate operation
if [ $1 = convw0 ]
then
	ln $2 fort.2||exit 1
	./$1 >>bigconv.out
	mv fort.1 $3||echo '**Failure**'
elif [ $1 = cplnq ]
then
	ln $2 fort.11||exit 1
	./$1 >>bigconv.out <<'End of input'
 &CARDS SKPHDR = T, CRDIN = T &END
End of input
	mv fort.12 $3||echo '**Failure**'
elif [ $1 = cpynbq ]
then
	ln $2 fort.11||exit 1
	./$1 >>bigconv.out <<'End of input'
 &INPUT IBODY=11,ITST=6,SKPHDR=T, JBODY=12, CRDIN=T &END
End of input
	mv fort.12 $3||echo '**Failure**'
elif [ $1 = cpynrm ]
then
	ln $2 fort.11||exit 1
	./$1 >>bigconv.out <<'End of input'
 &INPUT  CRDIN = T, CRDOUT = F &END
End of input
	mv fort.21 $3||echo '**Failure**'
elif [ $1 = cpyobs ]
then
	ln $2 fort.11||exit 1
	./$1 >>bigconv.out <<'End of input'
 &INPUT  CRDIN = T, PRNT = F, STATS = F, CUT = 2*0. &END
End of input
	mv fort.21 $3||echo '**Failure**'
elif [ $1 = ctchar ]
then
	ln $2 fort.3||exit 1
	./$1 >>bigconv.out <<'End of input'
 &INPUT  JEPH = 3, NEWEPH = 4 &END
End of input
	mv fort.4 $3||echo '**Failure**'
elif [ $1 = intrlv ]
then
	ln $2 fort.11||exit 1
	./$1 >>bigconv.out <<'End of input'
 &INPUT CRDIN = T, SKPHDR = T &END
End of input
	mv fort.12 $3||echo '**Failure**'
fi
