      SUBROUTINE ABCSRT(DATA,N,K)
C  DATA - ARRAY TO SORT, KEY IS 2ND WORD OF EACH ITEM, R*4
C  N    - NUMBER OF ITEMS IN ARRAY
C  K    - NUMBER OF FULLWORDS IN EACH ITEM
      INTEGER*4 N,K
      REAL*4 DATA(K,N)
C
      INTEGER*2 ABCCMP
      EXTERNAL ABCCMP
C
      CALL QSORT(DATA,N,4*K,ABCCMP)
      RETURN
      END
      FUNCTION ABCCMP(DATA1,DATA2)
      INTEGER*2 ABCCMP
      REAL*4 DATA1(2),DATA2(2)
C
      IF(DATA1(2).LT.DATA2(2)) THEN
         ABCCMP=-1
      ELSE IF(DATA1(2).EQ.DATA2(2)) THEN
         ABCCMP=0
      ELSE   
         ABCCMP=1
      ENDIF
      RETURN
      END
