C|BLKDAPP - BLOCK DATA FOR APPLE LASERWRITER VERSION OF ABC
      BLOCK DATA
      include 'plttyp.inc'
      DATA LOCALE,PROPOR,SYMHGT,PLTRNM /8, 0.700, 0.08, 'APPL LW'/
      DATA LPLEMS/0/
      DATA PLTRTC/0/
      END
