      SUBROUTINE DFT2(DATA,IPREV,IREM,N,ISIGN)
      DIMENSION DATA(IPREV,2,IREM)
      COMPLEX DATA,W,TEMP
      DO 10 I1=1,IPREV
      W=CEXP(CMPLX(0.,3.141593*FLOAT(ISIGN*(I1-1))/FLOAT(IPREV)))
      DO 10 I3=1,IREM
C     MULTIPLY BY THE PHASE SHIFT FACTOR.
      TEMP=W*DATA(I1,2,I3)
C     PERFORM A TWO-POINT FOURIER TRANSFORM IN PLACE.  NOTE THAT IT
C     CONSISTS OF ONLY AN ADDITION AND A SUBTRACTION.
      DATA(I1,2,I3)=DATA(I1,1,I3)-TEMP
10    DATA(I1,1,I3)=DATA(I1,1,I3)+TEMP
      RETURN
      END
