      SUBROUTINE GETSYM(ICASE)
      IMPLICIT NONE
C        ROUTINE TO FIGURE OUT  SYMBOLS TO USE FOR THE CURRENT SERIES OF
C        LOOKER PLOTS.SYMBOLS ARE CHOSEN SEQUENTIALLY FROM THREE RANGES
C        THE RANGE IS CHOSEN BY 'SYMCAS' WHICH SHOULD BE SET IN EACH
C        PROGRAM WHICH CALLS GETSYM
C        COMMON VARIABLE 'NSYM' CARRIES THE CALCOMP SYMBOL CODE.
C
C        INITIALIZATION: WHEN STARTING A PLOT THE FIRST CALL TO GETSYM
C        SHOULD HAVE ICASE<0.  GETSYM WILL SET NSYM TO THE FIRST SYMBOL
C        FOR THAT CASE. IT WILLTHEN NEGATE ICASE (MAKING IT POSITIVE),
C        ALLOWING PROPER CONTROL FOR SUBSEQUENT CALLS.
C
      INTEGER*4 ICASE
C
C        COMMONS
      include 'graphs.inc'
C
      INTEGER*4 MSYM
      CHARACTER*1 CSYM(4),OLDSYM
      EQUIVALENCE (MSYM,CSYM)
C
      IF(ICASE.LE.0) THEN
         MSYM=-1
         ICASE=-ICASE
      ENDIF
      IF(PLTSYM.NE.999) THEN
         NSYM=PLTSYM
         RETURN
      ENDIF
      OLDSYM=CSYM(4)
      MSYM=MSYM+1
      GO TO (100,200,300),ICASE
  100 IF(MSYM.EQ.   14) CSYM(4)='A'
  150 IF(OLDSYM.EQ.'I') CSYM(4)='J'
      IF(OLDSYM.EQ.'R') CSYM(4)='S'
      IF(OLDSYM.EQ.'Z') CSYM(4)='1'
      IF(OLDSYM.EQ.'9') MSYM=0
      GOTO 900
  200 IF(MSYM.EQ.   14) MSYM=0
      GOTO 900
  300 IF(OLDSYM.NE.'9' .AND. MSYM.NE.0) GOTO 150
      CSYM(4)='A'
  900 NSYM=MSYM
      RETURN
      END
