      SUBROUTINE LOOKER(MAXPT,DATA)
C         MAKE SEPARATE PASS THROUGH OBSLIB TAPE TO JUST PRINT AND/OR
C         PLOT DEPENDENT VARIABLE

      include 'pepglob.inc'
C
C        PARAMETERS
      REAL*4 DATA(9)
      INTEGER*4 MAXPT
C           DATA   - STORAGE ARRAY, TO BE INTERLEAVED
C                    (DEPVAR, INDEP.VAR., SYMBOL, ...)
C           MAXPT  - NUMBER OF FULLWORDS IN 'DATA'
C
C         COMMON
      include 'graphs.inc'
      CHARACTER*1 LSYM(4),PSYM
      EQUIVALENCE (LSYM(1),NSYM),(LSYM(4),PSYM)
      include 'inodtabc.inc'
      include 'misc.inc'
      include 'pltlab.inc'
      include 'plttyp.inc'
      include 'sortv.inc'
      include 'span.inc'
      include 't1a.inc'
      include 't2a.inc'
      include 't3a.inc'
C
C         LOCAL
      CHARACTER*8 TITLE(8)/' 10 1234',' SERA 14','DSMARS,1','4DSMARS:',
     1 '  5 JUPI','TER  GRS','P....',' '/
      CHARACTER*13 TITLOV/' Overall plot'/
      INTEGER*4 TLEN
      CHARACTER*1 TSYM,CSYMT(0:14)/'.','#','O','A','+','X','5',
     1 'T','K','Z','Y','%','*',':','|'/
      LOGICAL*4 PLT
      INTEGER*4 FOLD,IRC,PLMODE
      REAL*8 T,TREF,TMP,TIME,TIMLIM
      REAL*4 D,SIG
      INTEGER*4 JD0000/1721060/
C           SAVED SITE ARRAYS
      CHARACTER*8 ARRSIT(25,2)
      CHARACTER*4 ARRSYM(25)
      CHARACTER*1 SYMSAV(25)
      DATA NARSAV/25/
      INTEGER*4 SYMCAS
C
C        SETUP
      ISERIE=0
      KTOT=0
      PLMODE=0
      IF(ONEAXE) PLMODE=1
C        SYMBOL CASE: NOTE ORDER OF SYMCAS DETERMINATION
      NSYM=3
      IF(SYMBEL.AND.DOTPLT) NSYM=-1
      SYMCAS=-3
      IF(SYMBEL) SYMCAS=-2
      IF(SORT) SYMCAS=-1
      KKTH=IABS(KTH)
      FOLD=2
      IF(SORT) FOLD=3
      IF(HISTOG) FOLD=1
      NDAT=0
      MAXDAT=MAXPT-2*FOLD
      KPRINT = IPRINT
      IPRINT = 0
      IF(MOD(LOOK, 2) .EQ. 1) IPRINT = 1
      IF(MOD(LOOK/16,2).EQ.1) IPRINT=17
      PLT = MOD(LOOK/2, 2) .EQ. 1
      TREF=JDREF
      IF(NIV.NE.0) TREF=0D0
C
      ITMODE=TMODE
      IF(.NOT. PLT) GOTO 20
C           SET UP TITLE MODE FOR PLOTS
      IF(ONEAXE) GOTO 10
      IF(TMODE.EQ.3) TMODE=1
      GOTO 20
   10 IF(.NOT.SYMBEL) TMODE=0
      IF(TMODE.EQ.1) TMODE=3
   20 CONTINUE
      IF(HISTOG) TMODE=0
C
C **********************************************************************
C*  START=1000
C         READ TYPE 1 & 2 RECS
 1000 CALL RDLIB(1, IRC, T, D, TIME,SIG)
      IF(IRC .EQ. 1) GOTO 4020
      CALL RDLIB(2, IRC, T, D, TIME,SIG)
C
C         SERIES HEADER
 1010 CALL RDLIB(3, IRC, T, D, TIME,SIG)
C
C         EOF
      IF(IRC .EQ. 1) GOTO 1000
C
C         RESET OBS COUNTER
      K = 0
      SUM = 0.0
      KK = 0
      SUMY=0.0
      SUMX=0.0
C
C         READ OBS RECORD
 1020 CALL RDLIB(4, IRC, T, D, TIME,SIG)
 1025 CONTINUE
C
C         EOF OR END OF SERIES
      IF(IRC .GE. 1) GOTO 1500
C
C         SEE IF PLOTTING
      IF(.NOT. PLT) GOTO 1020
C
C         SEE IF SKIPPING ( KTH>1 ) OR AVERAGING ( KTH<-1 ) POINTS
C         ( KKTH = IABS(KTH) )
C        CHECK FOR HIGH PRECISION TIME ORIGIN
      IF(NIV.NE.0.OR..NOT.HIPREC) GOTO 1050
      IF(KK.GT.0.OR.K.GT.0) GOTO 1050
      I=T
      TMP=I
      IF(TMP.EQ.TREF) GOTO 1050
      IF(KTOT.GT.0) WRITE(PRINT,1040) TMP,SERA,TREF
 1040 FORMAT('0***WARNING: DATE=',F10.1,' FOR SERIES ',A4,
     1 ' DOES NOT MATCH REFERENCE DATE=',F10.1)
      TREF=TMP
      CALL EBCDI(I,XLAB(17:),8)
 1050 CONTINUE
      KK=KK+1
      IF(KTH .LE. 0) GOTO 1060
      IF(KK.LT.KKTH) GOTO 1020
      GOTO 1070
 1060 SUMY = SUMY + D
      SUMX = SUMX + (T - TREF)
      IF(KK .NE. KKTH) GOTO 1020
      D = SUMY/KKTH
      T = SUMX/KKTH + TREF
      SUMY=0.0
      SUMX=0.0
 1070 KK=0
C
C         SEE IF OUT OF SPACE
      IF(NDAT.GE.MAXDAT) GOTO 1020
C
C         CHECK FOR TIMESPAN LIMITS
      IF(K.EQ.0.AND.TSPAN.GT.0D0) TIMLIM=TIME+TSPAN
      IF(TSPAN.GT.0D0.AND.TIME.GT.TIMLIM) GOTO 1500
C
C         1ST HALF OF DATA HAS DEPENDENT VAR. 2ND HALF TIMES
      K = K + 1
      DATA(NDAT+1)=D
      SUM = SUM + D
      IF(.NOT.HISTOG) THEN
         DATA(NDAT+2)=T-TREF
         IF(JDREF.EQ.JD0000 .AND. NIV.EQ.0) 
     .    DATA(NDAT+2)=(T-TREF)/365.2425D0
      ENDIF
      NDAT=NDAT+FOLD
      GOTO 1020
C
C **********************************************************************
C*  START=1500
C            END OF SERIES -- GET READY TO PLOT IT
 1500 IF(.NOT. PLT) GOTO 4000
      IF(K.LE.0) GOTO 4000
C
C        SET UP TITLES FOR X AND Y AXES
      I=TREF
      IF(I.EQ.JD0000 .AND. NIV.EQ.0) THEN
         LLX=9
         XLAB(1:LLX)='Date (yr)'
      ELSE
         CALL EBCDI(I,XLAB(17:),8)
         CALL SETLAB(XLAB,LLX,NIV,OBSNM1,OBSUN1,OBSLU1)
      ENDIF
      CALL SETLAB(YLAB,LLY,NDV,OBSNM,OBSUN,OBSLU)
C
C         FOR ALSEP FREQUENCY PLOTS (SAVE(6,7)), USE DISTANCE FROM MEAN
C         FREQUENCY
      IF((NDV .NE. -6) .AND. (NDV .NE. -7)) GOTO 1520
      IF(NPLNTA.NE.10) GOTO 1520
      SUM = SUM/K
      ID=NDAT+1
      DO 1510 I = 1, K
      ID=ID-FOLD
 1510 DATA(ID)=DATA(ID)-SUM
 1520 CONTINUE
C          SYMBOL: TYPE OF SYMBOL DETERMINED BY SYMCAS SET EARLIER
C          GET SYMBOL (FOR ONEAXE PLOTS ONLY)
C          RETURNS SYMBOL NUMBER IN COMMON VARIABLE NSYM
      IF(.NOT.ONEAXE) GOTO 1560
      IF(SYMOPT) GOTO 1530
      CALL GETSYM(SYMCAS)
      GOTO 1560
 1530 IF(ISYMNO.LE.0) GOTO 1550
      DO 1540 IS=1,ISYMNO
      IF(ARRSIT(IS,1).NE.SITA .OR.
     1   ARRSIT(IS,2).NE.RITA .OR.
     2   ARRSYM(IS).NE.SERA) GOTO 1540
      PSYM=SYMSAV(IS)
      GOTO 1560
 1540 CONTINUE
 1550 IF(ISYMNO.LT.NARSAV) ISYMNO=ISYMNO+1
      ISYMNX=ISYMNX+1
      IF(ISYMNX.GT.NARSAV) ISYMNX=1
      CALL GETSYM(SYMCAS)
      ARRSIT(ISYMNX,1)=SITA
      ARRSIT(ISYMNX,2)=RITA
      ARRSYM(ISYMNX)=SERA
      SYMSAV(ISYMNX)=PSYM
 1560 CONTINUE
C
      IF(.NOT. HISTOG) GOTO 2000
      CALL HSTGRM(PLMODE,DATA,K,1)
      GOTO 2035
C
C **********************************************************************
C*  START=2000
C          SORTING AND PLOTTING
C                  PLOTTING: PLOTTING IS DONE ONE SERIES AT A TIME
C     THERE ARE TWO TYPES OF PLOTS: NORMAL - ONE SERIES OF DATA PER PLOT
C     AND ONEAXE - ALL SERIES ON ONE PLOT.
C                  SORTING
C             FOR ONEAXE PLOTTING, THE DATA POINTS WILL BE WRITTEN TO A
C     TEMPORARY STORAGE BY 'SORTER' ONE SERIES AT A TIME. AS THIS IS
C     DONE THEIR MAX AND MIN WILL BE CALCULATED FOR USE IN PLOTTING.  A
C     SYMBOL, SPECIFIC TO THAT SERIES, IS ALSO SORTED SO THAT EACH
C     POINT CAN BE LABELED.  ACTUAL SORTING IS INITIATED BY THE CALL
C     TO 'SRTPLT' MADE AFTER ALL SERIES ARE PASSED TO BE SORTED. THIS
C     ROUTINE ALSO INITIATES PLOTTING.
C             NON-ONEAXE SORTED PLOTS ARE HANDLED SIMILARLY
C
C           SET UP TITLE
 2000 CONTINUE
      CALL EBCDI(NTAPA,TITLE,3)
      CALL EBCDIX(NSEQA,TITLE,4,5)
      CALL MVC(SERA,1,4,TITLE,10)
      CALL MVC(RITA,1,8,TITLE,15)
      CALL MVC(SITA,1,8,TITLE,24)
      N=NPLNTA
      CALL EBCDI(N,TITLE(5),3)
      CALL MVC(PNAMA,1,8,TITLE,37)
      CALL MVC(SPOTA,1,4,TITLE,46)
      CALL MVC(SPOT2A,1,4,TITLE,50)
      TLEN=53
      CALL MVC('        ',1,8,TITLE,TLEN+1)
      IF(TSPAN.NE.0D0) THEN
         I=TIMLIM
         CALL EBCDIX(I,TITLE,TLEN+1,8)
         TLEN=TLEN+8
      ENDIF
      PTITLE(1:8)=R1A(2)
      PTITLE(9:16)=R1A(1)
      PTITLE(17:24)=R1A(11)
      CALL MVC(TITLE,1,TLEN,PTITLE,25)
      LLT=TLEN+24
      TSYM=PSYM
      IF(NSYM.LE.13) TSYM=CSYMT(NSYM+1)
      WRITE(PRINT,2010) TSYM,TITLE
 2010 FORMAT(10X,'(',A1,')  ',10A8)
      IF(TMODE.EQ.3) CALL TITEL(TITLE,TLEN,THGT,0.15)
 2020 IF(SORT) THEN
         ID=NDAT-K*FOLD+1
         CALL SORTER(PLMODE,DATA(ID),K,FOLD)
         IF(ONEAXE) GOTO 2040
C           PLOT IMMEDIATELY
         CALL SRTPLT(PLMODE,DATA,K,FOLD)
      ELSE
         CALL PLOTER(PLMODE,DATA(2),DATA(1),K,FOLD)
      ENDIF
C
 2035 NDAT=0
C
 2040 CONTINUE
      IF(ONEAXE) PLMODE=2
C
C **********************************************************************
C*  START=4000
C        FINISHED THIS SERIES -- DO ANOTHER?
 4000 ISERIE = ISERIE + 1
      KTOT=KTOT+K
C        RESET NOW, IN CASE DOING SPAN-LIMITED PLOTS
      K=0
      SUM=0.
      KK=0
      SUMX=0.
      SUMY=0.
      IF(ISERIE.GE.NSERIE) GOTO 4010
      IF(TSPAN.GT.0D0.AND.TIME.GT.TIMLIM) GOTO 1025
      IF(IRC.EQ.1) GOTO 1000
      GOTO 1010
C
C           REWIND TAPES AND RESET
 4010 CALL RDLIB(0,IRC,T,D,TIME,SIG)
C           FINISHED TAPE READING
C           CHECK IF ANY ONEAXE PLOTTING TO CLEAN UP
 4020 IF(KTOT.LE.0) GOTO 4040
      IF(.NOT.(ONEAXE.AND.PLT)) GOTO 4040
      IF(HISTOG) THEN
         CALL HSTGRM(3,0.,KTOT,1)
      ELSE
         CALL MVC(TITLOV,1,13,PTITLE,25)
         IF(SORT) THEN
            CALL SRTPLT(0,DATA,KTOT,FOLD)
         ELSE
            CALL PLOTER(3,0.,0.,0,1)
         ENDIF
      ENDIF
 4040 IPRINT=KPRINT
      TMODE=ITMODE
      RETURN
      END
