      SUBROUTINE NUMBER(X,Y,HT,FLT,THETA,N)
C PLOT A NUMBER AS A CHARACTER STRING
C
      IMPLICIT NONE
C
      REAL*4 X,Y,HT,FLT,THETA
      INTEGER*4 N
C  X,Y  - STARTING COORDINATES OF STRING
C  HT  -  HEIGHT OF CHARACTERS
C  FLT  - NUMBER TO PLOT
C  THETA- ORIENTATION ANGLE OF STRING (CCW FROM +X AXIS)
C  N -    NUMBER OF DIGITS AFTER DECIMAL POINT.  IF -1, OMIT THE
C         DECIMAL POINT ALTOGETHER, IF <-1, TRUNCATE DIGITS ON THE
C         RIGHT AFTER ROUNDING
C
      REAL*4 AFLT,ROUND,RNUM
      INTEGER*4 NROUND,INDX,NBL,NBR,DIGIT,ONE,ZERO,UNIT,I
      CHARACTER*20 STRING
      CHARACTER*4 CDIG,CZER,CONE
      EQUIVALENCE (DIGIT,CDIG),(ZERO,CZER),(ONE,CONE)
      DATA CZER/'  0 '/, CONE/'  1 '/
C
      UNIT=ONE-ZERO
      INDX=0
C           GET SIGN OF NUMBER
      AFLT=ABS(FLT)
      IF(FLT.LT.0.) THEN
         INDX=INDX+1
         STRING(1:1) = '-'
      ENDIF
C           GET ROUNDING
      ROUND=0.5
      IF(N.GT.0 .OR. N.LT.-1) THEN
         NROUND=N
         IF(N.LT.-1) NROUND=N+1
         ROUND=0.5*(10.**(-NROUND))
      ENDIF
C           NUMBER OF DIGITS TO LEFT OF DECIMAL
      RNUM=AFLT+ROUND
      NBL=0
      DO WHILE (RNUM.GE.1.)
         NBL=NBL+1
         RNUM=RNUM*0.1
      END DO
C           NUMBER OF DIGITS TO RIGHT OF DECIMAL
      NBR=N
      IF(NBL.EQ.0) THEN
         IF(AFLT.LT.ROUND) THEN
            INDX=0
            IF(NBR.GT.1) NBR=1
         ENDIF
         INDX=INDX+1
         STRING(INDX:INDX)=CZER(3:3)
      ENDIF
C           COLLECT DIGITS TO THE LEFT
      IF(N.LT.0) NBL=MAX0(NBL+1+N,0)
      DO I=1,NBL
         RNUM=RNUM*10.
         DIGIT=IFIX(RNUM)*UNIT+ZERO
         INDX=INDX+1
         STRING(INDX:INDX)=CDIG(3:3)
         IF(INDX.EQ.20) GOTO 100
         RNUM=AMOD(RNUM,1.)
      END DO
      IF(N.GE.0) THEN
         INDX=INDX+1
         STRING(INDX:INDX)='.'
C           COLLECT DIGITS TO THE RIGHT
         DO I=1,NBR
            RNUM=RNUM*10.
            DIGIT=IFIX(RNUM)*UNIT+ZERO
            INDX=INDX+1
            STRING(INDX:INDX)=CDIG(3:3)
            IF(INDX.EQ.20) GOTO 100
            RNUM=AMOD(RNUM,1.)
         END DO
      ENDIF
  100 CALL SYMBOL(X,Y,HT,STRING,THETA,INDX)
      RETURN
      END
