      SUBROUTINE PHSPMA(NPLNT, K, NAMES, LVEC,N,SITE,SERIES)
C         GENERATES NAMES FOR OPTICAL PHASE CORRECTIONS
C         (NAME FORMAT NOT IMPLEMENTED - THROWS IN BLANKS)
C
C         PARAMETERS
      CHARACTER*8 NAMES(2, 1)
      INTEGER*4 K, NPLNT
      INTEGER*2 LVEC(1), N
      CHARACTER*4 SITE,SERIES
C
C         LOCALS
      CHARACTER*4 WD1H(2)
      CHARACTER*8 TEMP,WD1,WD2/'PL00PHC0'/
      CHARACTER*1 MINUS/'-'/
      EQUIVALENCE (WD1H(1),WD1)
      CHARACTER*1 NUMS(9)/'1','2','3','4','5','6','7','8','9'/
C
C         LOOP THRU PHASES
      IF (N .LE. 0) RETURN
      WD1H(1)=SITE
      WD1H(2)=SERIES
      TEMP=WD2
      NP=IABS(NPLNT)
      NPP=NP/10
      IF(NPP.GT.0) TEMP(3:3)=NUMS(NPP)
      NPP=MOD(NP,10)
      IF(NPP.GT.0) TEMP(4:4)=NUMS(NPP)
      IF(NPLNT.LT.0) TEMP(3:3)=MINUS
      DO 20 I = 1, N
      IF (LVEC(I) .EQ. 0) GO TO 20
      K = K + 1
      NAMES(1,K)=WD1
      TEMP(8:8)=NUMS(I)
      NAMES(2,K)=TEMP
 20   CONTINUE
      RETURN
      END
