      SUBROUTINE PLAXIS(MODE)
C          IT DRAWS THE X- AND THE Y- AXES
C
C        PARAMETERS
C           MODE- SELECTOR FOR WHICH AXIS  (AXES) TO DRAW
C                  0: PLOT JUST Y-AXIS
C                  1: PLOT JUST X-AXIS
C                  2: PLOT BOTH AXES
C
      INTEGER*4 MODE
C
C        COMMON
      include 'burst.inc'
      include 'graphs.inc'
      include 'pltfrm.inc'
      include 'pltlab.inc'
      include 'plttyp.inc'
      include 'sortv.inc'
C           X0  - LOWER LIMIT OF X FOR CURRENT PLOT
C           X1  - NEXT X VALUE (IF ANY) TO BE PLOTTED
C           X2  - UPPER LIMIT OF X FOR CURRENT PLOT
C
C        LOCALS
      REAL*4 X3,XZ,YZR
      INTEGER*4 MM,IRU
C
      IRU=IBURST
      IF(MODE.EQ.0) GOTO 200
C           FIND X-AXIS LENGTH
      IF(IBURST.LE.1)GO TO 100
      MM=X2/SCONVX
      X3=MM*SCONVX
      IF(X3.LE.X2)X3=X3+SCONVX
      X2=X3
C
      XL=DINT((X2-SMINX)/SCONVX+0.1)
C
  100 CONTINUE
      IF(DUAL.NE.2)
     1 CALL AXIS(0.,0.,XLAB,-LLX,XL,0.0,SMINX,SCONVX,DIVX)
      MM=-LLY
      IF(DUAL.EQ.2) GOTO 105
C
C       DRAW ZERO LINE
      IF(.NOT.ZLINE) GOTO 110
      MM=-999
      IF(SMINY.GE.SCONVY*0.01) GOTO 105
      YZR=-SMINY/SCONVY
      IF(YZR.GE.YL-0.01) GOTO 105
      CALL PLOT(0.,YZR,3)
      CALL PLOT(XL,YZR,2)
C           DRAW BOX AROUND PLOT
  105 CALL AXIS(XL,0.,YLAB,MM,YL,90.,SMINY,SCONVY,DIVY)
      MM=999
      IF(TMODE.EQ.2.OR.TMODE.EQ.4) MM=-999
      CALL AXIS(0.,YL,' ',MM,XL,0.,SMINX,SCONVX,DIVX)
C
  110 CONTINUE
      CALL FACTOR(1.0)
      XZ=XORG+XL*FACT+XMRG+2.0
      IF(XZ.GT.XEND) XEND=XZ
      IF(MOD(TMODE,2).EQ.0) CALL TITEL(PTITLE,LLT,THGT,0.25)
      YEND=YEND+1.5
      IF(MODE.EQ.1)RETURN
C           CONTINUATION PLOT - MOVE RIGHT
      IRU=1
C
C           PLOT Y-AXIS
  200 CONTINUE
      IF(DUAL.EQ.2) GOTO 250
      IF(TMODE.EQ.1) CALL TITEL(PTITLE,LLT,THGT,XMRG)
      CALL PLNEXT(XLNOM*FACT,YLEN*FACT,IRU)
  250 CALL FACTOR(FACT)
      IF(DUAL.EQ.2) GOTO 500
      CALL AXIS(0.0,0.0,YLAB,LLY,YL,90.0,SMINY,SCONVY,DIVY)
      IF(IBURST.LT.2)GO TO 500
      MM=X1/SCONVX
      SMINX=MM*SCONVX
      IF(SMINX.GE.X1)SMINX=SMINX-SCONVX
  500 CONTINUE
      X0=SMINX
      MODPLT=1
      RETURN
      END
