      SUBROUTINE TITEL(STRING, LENGTH, HEIGHT, SPACE)
      IMPLICIT NONE

C WRITE A TITLE.  TYPE IS DEDUCED FROM LENGTH: 88=>TAPE, OTHER=>PLOT
C ORIENTATION IS GOVERNED BY 'TMODE', WHICH DEPENDS PARTLY ON 'ONEAXE'.
C IF VERTICALLY ACROSS PLOT, THEN MOVE ORIGIN A SPACE TOWARD +X AFTER.
C IF HORIZONTALLY, THEN MOVE TOWARD +Y AFTER, UNLESS 'TMODE' IS 2 OR 4.
C
C         PARAMETERS
      CHARACTER*1  STRING(1)
      INTEGER*4  LENGTH
      REAL*4  HEIGHT, SPACE
C
C         COMMON
      include 'graphs.inc'
      include 'pltfrm.inc'
      include 'plttyp.inc'
C
C        LOCAL
      REAL*4 XLZ,HLN,YHO
C
      IF(TMODE.LE.0) RETURN
      IF(PFIRST) CALL PLNITL
      XLZ=HEIGHT*PROPOR*LENGTH+0.5
      IF(TMODE.NE.1) GOTO 200
  100 CALL PLNEXT(SPACE+XLNOM*FACT,XLZ,1)
      XEND=XEND+SPACE
C
C         WRITE TITLE AND SPACE
      CALL SYMBOL (0.0, 0.0, HEIGHT, STRING, 90.0, LENGTH)
      RETURN
C
  200 IF(TMODE.NE.2) GOTO 300
      IF(LENGTH.EQ.88) GOTO 100
  210 IF(YEND+HEIGHT.GT.YFRAME) RETURN
      CALL SYMBOL(0.0,YEND+0.05-YORG,HEIGHT,STRING,0.0,LENGTH)
      XLZ=XORG+XLZ
      IF(XLZ.GT.XEND) XEND=XLZ
      YEND=YEND+SPACE
      RETURN
C
C         ONE AXES LABELS SPREAD HORIZ. BELOW EACH OTHER
  300 IF(TMODE.NE.3) GOTO 400
      IF((.NOT.TFIRST).AND.XORG.GT.XMRG) GOTO 320
  310 CALL PLNEXT(HLEN,YFRAME,1)
      CALL PLOT(HLEN,0.,-3)
      XORG=XORG+HLEN
      XEND=XORG
      XOMIN=XORG
      YEND=YORG
      YH=YMRG
      TFIRST=.FALSE.
  320 IF(YH+HEIGHT.LE.YFRAME) GOTO 350
      IF(XEND.LE.XORG) GOTO 310
      RETURN
  350 HLN=0.5-HLEN
      YHO=YH-YORG
      IF(LENGTH.EQ.88) GOTO 370
C           NOT A TAPE TITLE
      CALL SYMBOL(1.0-HLEN,YHO+HEIGHT*0.5,HEIGHT,NSYM,0.0,-1)
      HLN=1.5-HLEN
C
  370 CALL SYMBOL(HLN,YHO,HEIGHT,STRING,0.0,LENGTH)
      YH=YH+HEIGHT*1.5
      RETURN
C
C           NO TAPE TITLES
  400 IF(LENGTH.EQ.88) RETURN
C           PLOT TITLES AS IN TMODE=2
      GOTO 210
C
      END
