      SUBROUTINE DUMSTF
      ENTRY ASCII(A,B)
      ENTRY OPRMSG(A,B)
      ENTRY ERRSET(A,B,C,D,E,F)
      ENTRY FILEINF(A,B,C)
      ENTRY PLOG(A)
      ENTRY PLOG0
      ENTRY PLOG9
      ENTRY NOUNDR
      ENTRY UNDRON
      ENTRY SNPDMP
C     ENTRY ANALIZ
C     ENTRY PRDICT(A,B,C)
C     ENTRY PSRPAR(A)
C     ENTRY PSRPHS(A)
C     ENTRY SBFOUT(A,B)
      RETURN
      END
