C           TARGET BODY GRAVITATIONAL POTENTIAL HARMONICS
      COMMON/TRGHAR/ TRAD(i_mxtrg),TZHAR(i_mxtrg,4),TCHAR(i_mxtrg,5),
     1 TSHAR(i_mxtrg,5),ALPHT(i_mxtrg,2),DELTT(i_mxtrg,2),
     2 CALPHT(i_mxtrg),SALPHT(i_mxtrg),CDELTT(i_mxtrg),SDELTT(i_mxtrg),
     3 EPOCHT(i_mxtrg),PSIT0(i_mxtrg),OMEGT(i_mxtrg),KTHAR(i_mxtrg),
     4 NTZONE(i_mxtrg),NTZON1(i_mxtrg),NTTESS(i_mxtrg),NTTES1(i_mxtrg),
     5 NTTES2(i_mxtrg),NTOPT(i_mxtrg),ITZONE(i_mxtrg,4),JTZONE(i_mxtrg),
     6 ITCOS(i_mxtrg,5),JTCOS(i_mxtrg),ITSIN(i_mxtrg,5),JTSIN(i_mxtrg)
      REAL*10 TRAD,TZHAR,TCHAR,TSHAR,ALPHT,DELTT,CALPHT,SALPHT,CDELTT,
     1 SDELTT,EPOCHT,PSIT0,OMEGT
      INTEGER*4 KTHAR,NTZONE,NTZON1,NTTESS,NTTES1,NTTES2,NTOPT,ITZONE,
     1 JTZONE,ITCOS,JTCOS,ITSIN,JTSIN
