      SUBROUTINE CRD(I)
      IMPLICIT NONE
 
C        READ A CARD FROM FILE I IF NOT ALREADY AT EOF
      INCLUDE 'aplst.inc'
C        CARD BUFFERS - SIZE DEFINED HERE
      COMMON /BUFFER/ CBF(48000)
      CHARACTER*1 CBF
      include 'chars.inc'
      include 'ibfl.inc'
      include 'pgfba.inc'
      include 'ptrs.inc'
C
      INTEGER*4 ICP(2),I,IINC,IPN,J,K,LNM,LNN,LNPRV,LSUP
      CHARACTER*1 TST
C
      IF(IEF(I).EQ.1) RETURN
      IF(JP(I).EQ.0) ICP(I)=IBFLL(I)
      LSUP=0
      LNPRV=ICP(I)
      ICP(I)=IINC(ICP(I),I)
      LNM=ICP(I)
      LNN=LNM-1+JSIZ
      IF(IRFM.NE.0) GOTO 200
      READ(I,60,END=800) (CBF(J),J=LNM,LNN)
   60 FORMAT(4(250A1))
  100 JP(I)=JP(I)+1
      RETURN
C
C           READ PRINT LINE & SAVE FIRST CHARACTER
  200 READ(I,60,END=800) TST,(CBF(J),J=LNM,LNN)
      IF(TST.NE.CHAN(1)) GOTO 230
C           COUNT PAGES
      IPGN(I)=IPGN(I)+1
C           SAVE CUMULATIVE LINE NUMBER
      IPN=IPNP(I)+1
      IF(IPN.LE.NKPG) GOTO 220
C           OVERFLOWED BUFFER, SHIFT ALL PTRS
      DO 210 K=1,NKPG
  210 KPGP(I,K)=KPGP(I,K+1)
      IPN=NKPG
      IF(IIP.GT.1) IIP=IIP-1
  220 KPGP(I,IPN)=JP(I)
      IPNP(I)=IPN
C        CHECK FOR END OF PAGE REGION
      IPN=KSPG(I)
      IF(IPN.GT.ISPG(I)) GOTO 225
      IF(IPGN(I).LE.SPG(IPN,I)) GOTO 225
      KSPG(I)=KSPG(I)+1
      IIPG(I)=1-IIPG(I)
  225 CONTINUE
      IF(IRFM.GT.2) GOTO 300
C           CHECK FOR ALL BLANKS
  230 IF(IIPG(I).EQ.0) GOTO 300
      IF(LSUP.NE.0.OR.JP(I).LE.LN(I)) GOTO 235
      IF(TST.NE.CHAN(3)) GOTO 235
C        MERGE AN OVERPRINTED RECORD
      K=LNPRV-1
      DO 233 J=LNM,LNN
      K=K+1
      IF(CBF(J).NE.BLANK) CBF(K)=CBF(J)
  233 CONTINUE
      LOOK=LOOKS
      GOTO 200
  235 CONTINUE
      IF(IRFM.EQ.1) GOTO 100
      DO 240 J=LNM,LNN
      IF(CBF(J).NE.BLANK) GOTO 250
  240 CONTINUE
      GOTO 300
C           CHECK FOR OTHER CONTROLS
  250 IF(IRFM.LT.4) GOTO 100
      IF(TST.EQ.CHAN(2)) GOTO 100
C        SUPPRESS THIS LINE
  300 ISUP(I)=ISUP(I)+1
      LSUP=1
      GOTO 200
C           REACHED END OF FILE
  800 IEF(I)=1
      RETURN
      END
