      SUBROUTINE DSNAME(IUNIT,FNAME,ICODE)
      IMPLICIT NONE
 
      INTEGER*4 IUNIT,ICODE
      CHARACTER*60 FNAME
      INTEGER*4 IOC
 
      ICODE=1
      CLOSE(IUNIT)
      IF(IUNIT.NE.7) THEN
         IF(FNAME(1:9).EQ.'NULLFILE ') RETURN
         OPEN(IUNIT, FORM='FORMATTED', FILE=FNAME, IOSTAT=IOC,
     .    STATUS='OLD')
      ELSE IF(FNAME(1:9).EQ.'NULLFILE ') THEN
         OPEN(IUNIT, FORM='FORMATTED', IOSTAT=IOC, STATUS='SCRATCH')
      ELSE
         OPEN(IUNIT, FORM='FORMATTED', FILE=FNAME, IOSTAT=IOC)
      ENDIF
      IF(IOC.EQ.0) ICODE=0
      RETURN
      END
