      SUBROUTINE EDITL(ISTRT,IFIN,NDIM,MAX,NPAIR)
      IMPLICIT NONE
 
C        EDIT LISTS OF START AND FINISH NUMBERS FOR CONSISTENCY
C        REMOVE ANY EXTRANEOUS PAIRS, CONSOLIDATE CONTIGUOUS PIECES
C        ASSUME FIRST PAIR ( ISTRT(1) - IFIN(1) ) IS ALREADY OK.
      INTEGER*4 NDIM,ISTRT(NDIM),IFIN(NDIM),MAX,NPAIR
 
      INTEGER*4 I,J,MIN
C
      J=2
      MIN=MIN0(ISTRT(1),IFIN(1))
      DO 520 I=2,NDIM
      IF(IFIN(J-1).GE.MAX) GOTO 530
      IF(ISTRT(I).LT.MIN) GOTO 530
      IF(ISTRT(I)-1.GT.IFIN(I-1)) GOTO 510
C        OVERLAP, REMOVE ONE PAIR FROM LIST
      J=J-1
      ISTRT(I)=ISTRT(J)
      IF(IFIN(I).LT.IFIN(J)) IFIN(I)=IFIN(J)
  510 ISTRT(J)=MIN0(ISTRT(I),MAX)
      IFIN(J)=MIN0(MAX,MAX0(IFIN(I),ISTRT(J) ) )
      J=J+1
  520 CONTINUE
  530 NPAIR=J-1
  600 RETURN
      END
