      INTEGER FUNCTION IINC(IPTR,I)
      IMPLICIT NONE
      INTEGER*4 IDEC, IPTR, I
 
C   INCREMENT BUFFER PTR FOR NEXT CARD - CHECK FOR END OF BUFFER
C   'I' INDICATES WHICH FILE - 1 OR 2
      include 'ibfl.inc'
      include 'ptrs.inc'
C
      IINC=IPTR+JSIZ
      IF(IINC.GT.IBFLL(I)) IINC=ISUB1(I)
      RETURN
      ENTRY IDEC(IPTR,I)
      IDEC=IPTR-JSIZ
      IF(IDEC.LT.ISUB1(I)) IDEC=IBFLL(I)
      RETURN
      END
