      SUBROUTINE UDIFF(BUFA,BUFB,OUT,LEN,ICODE)
      IMPLICIT NONE
 
C    BUFA      FIRST LINE OF TEXT
C    BUFB      SECOND LINE OF TEXT, PRESUMED SIMILAR TO BUFA
C    OUT       OUTPUT BUFFER TO CONTAIN BLANKS AND UNDERSCORES
C    LEN       LENGTH OF THE THREE BUFFERS (IN BYTES)
C    ICODE     RETURN CODE: 0 IF BUFA=BUFB, 1 IF NOT
 
      INTEGER*4 LEN,ICODE
      CHARACTER*1 BUFA(LEN),BUFB(LEN),OUT(LEN)
C
C        SUBROUTINE UDIFF COMPARES TWO LINES OF TEXT AND FORMS
C        A 'DIFFERENCE' BUFFER CONTAINING BLANKS WHEREVER THE TWO
C        AGREE AND UNDERSCORES WHERE THEY DISAGREE.  IF THE TWO
C        LINES ARE IDENTICAL, THE ROUTINE SIMPLY RETURNS A CODE
C        OF 0 RATHER THAN FORMING THE OUTPUT BUFFER.
 
      INTEGER*4 I
C
      ICODE=0
      DO 100 I=1,LEN
      OUT(I)=' '
      IF(BUFA(I).EQ.BUFB(I)) GOTO 100
      OUT(I)='_'
      ICODE=1
  100 CONTINUE
      RETURN
      END
