      SUBROUTINE VINPUT(ICALL)
      IMPLICIT NONE
C       SET ALL FLAGS TO DEFAULT VALUES, THEN READ INPUT OVERRIDES
C       ON FIRST CALL, SPOOL INPUT TO TEMPORARY DATASET & PRINT
      INTEGER*4 ICALL
 
      include 'aplst.inc'
      INTEGER*4 PG1ST(5),PG2ST(5),PG1FN(5),PG2FN(5),SPG4(20)
      EQUIVALENCE (SPG4(1),PGS(1,1),PG1ST(1)),
     1            (PGS(1,2),PG2ST(1)),(PGF(1,1),PG1FN(1)),
     2            (PGF(1,2),PG2FN(1))
 
      include 'chars.inc'
      include 'dflt.inc'
      include 'lcmp.inc'
      include 'pgfba.inc'
      include 'ptrs.inc'
C
      NAMELIST/CNTL/ JSIZ,IRFM,CHAN,IPUN,ISQN,LCMP,JCL,KFIN,ISTRT,IFIN,
     1 PG1ST,PG2ST,PG1FN,PG2FN,NOPRNT,FNAME
      CHARACTER*4 CARD(20), BLNK4/'    '/
      INTEGER*4 ISPL/4/, ISW, ICRD, I
      CHARACTER*8 QTYP(2)/' MERGED ', 'DEFAULT '/
C
      IF(ICALL.GT.0) GOTO 300
C       INITIALIZE INPUT
      IEND5=0
      ICRD=0
   90 READ(5,100,END=200) CARD
  100 FORMAT(20A4)
      ICRD=ICRD+1
      WRITE(6,110) CARD
  110 FORMAT(1X,20A4)
      CARD(19)=BLNK4
      CARD(20)=BLNK4
      WRITE(ISPL,100) CARD
      GOTO 90
C       END OF INPUT STREAM
  200 IF(ICRD.EQ.0) GOTO 300
      WRITE(6,210) ICRD
  210 FORMAT(1X,18('----'),'XXXXXXXX END INPUT AFTER',I4,' CARDS')
      REWIND ISPL
C
C       SET DEFAULT VALUES
  300 JSIZ=JSIZD
      IRFM=IRFMD
      DO 305 I=1,3
  305 CHAN(I)=CHAND(I)
      FNAME(1)(1:9)='NULLFILE '
      FNAME(2)(1:9)='NULLFILE '
      IPUN=IPUND
      ISQN=ISQND
      LCMP=LCMPD
      JCL=JCLD
      KFIN=KFIND
      NOPRNT=NOPRTD
      DO 330 I=1,8
      ISTRT(I)=0
  330 IFIN(I)=0
      DO 340 I=1,20
  340 SPG4(I)=-1
C           CHECK FOR END OF INPUT
      IEND5=IEND5+1
      IF(IEND5.GT.1) GOTO 500
      IF(ICRD.EQ.0) GOTO 400
      READ(ISPL,CNTL,END=350)
      IEND5=0
  350 IF(JSIZ.LE.0) JSIZ=80
      IF(ISQN.NE.0) ISQN=1
      IF(JCL.NE.0) JCL=1
      IF(KFIN.LE.0) KFIN=72
      IF(IRFM.LT.0) IRFM=0
  400 ISW=1
      IF(ICALL.NE.0) GOTO 410
      ISW=2
C           SAVE NEW VALUES AS DEFAULTS
      JSIZD=JSIZ
      IRFMD=IRFM
      DO 405 I=1,3
  405 CHAND(I)=CHAN(I)
      IPUND=IPUN
      ISQND=ISQN
      LCMPD=LCMP
      JCLD=JCL
      KFIND=KFIN
      NOPRTD=NOPRNT
  410 IF(NOPRNT.GT.0) GOTO 500
      WRITE(6,420) QTYP(ISW),JSIZ,IRFM,IPUN,ISQN,LCMP,JCL,KFIN,CHAN
  420 FORMAT('0',A8,'FLAGS:  JSIZ=',I3,'  IRFM=',I2,
     1 '  IPUN=',I2,'  ISQN=',I1,'  LCMP=',I2,'  JCL=',I1,'  KFIN=',I3,
     2 '  CHAN=''',A1,1H',2(2H,',A1,1H'))
  500 IF(ICALL.EQ.0) GOTO 600
      IF(ISTRT(1).LT.1) ISTRT(1)=1
      IF(IFIN(1).LT.1) IFIN(1)=KFIN
C        EDIT LIST FOR CONSISTENCY
      CALL EDITL(ISTRT,IFIN,8,JSIZ,ISF)
C        SET UP PAGE LISTS
      DO 510 I=1,2
      IF(PGS(1,I).LT.0) PGS(1,I)=0
      IF(PGF(1,I).LT.0) PGF(1,I)=32000
      CALL EDITL(PGS(1,I),PGF(1,I),5,32000,ISPG(I))
  510 CONTINUE
  600 RETURN
      END
